#sourse of data
#spring boot send logs to port 5000. From here we get logs
#We wait data in json
input {
  tcp {
    port => 5000
    codec => json
  }
}

#kuda mi otpravlyaem obrabotanie danie
#every time will be create new file. Ex: spring-logs-2025.07.08
output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "spring-logs-%{+YYYY.MM.dd}"
  }
}