spring.application.name=inopolis

# ????????? ?????? ????????? Actuator
management.endpoints.web.exposure.include=health,metrics,prometheus

# ?????????? ?????? ???????? (??????? ??)
management.endpoint.health.show-details=always

# ????????? ??? ? ????????
management.metrics.tags.application=my-app
