spring.application.name=inopolis

#Actuator
management.endpoints.web.exposure.include=health,metrics,prometheus

management.endpoint.health.show-details=always

management.metrics.tags.application=my-app

# Datasource settings for H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# JPA settings
spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 console settings
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.properties.hibernate.format_sql=true

